services:
    db:
        container_name: db
        image: postgres:latest
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - PGPORT=${DB_PORT}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    app:
        build: .
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - db
        environment:
            HOST: ${HOST}
            PORT: ${PORT}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
volumes:
    pgdata: